### ISSUE TITLE
Template syntax issues

### ISSUE THREAD

**Issue by zzc-river** [akto-api-security/tests-library#172]
Lack-of-Resources-and-Rate-Limiting/DateFieldInputDoS.yml
I finally found the problem. In your official template, extract is not indented, which causes the value to not be replaced with a dictionary list.
![image](https://github.com/user-attachments/assets/432ed338-fe61-426e-bc47-891eaf96367b)

**Comment by arjun-akto** [comment]
Thanks for reporting the issue, @zzc-river. We'll work on it.

**Comment by arjun-akto** [comment]
Fix has been released, @zzc-river. Thank you for reporting it!
